version: '3'
services:
  web:
    container_name: file_upload_vulnerabilities
    build:
      context: ./src
      dockerfile: Dockerfile
    # volumes:
    #   - ./src:/var/www/html/
    ports:
      - 8000:80