version: '3'
services:
  web:
    container_name: file_upload_vulnerabilities
    
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
       - ./.docker/000-default.conf:/etc/apache2/sites-available/000-default.conf
    # volumes:
    #   - ./src:/var/www/html/
    ports:
      - 8000:80